name: sass
version: 1.30.0
description: A Sass implementation in Dart.
author: Sass Team
homepage: https://github.com/sass/dart-sass

executables:
  dart-sass: sass
  sass: sass

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  args: ">=1.4.0 <2.0.0"
  async: ^2.5.0-nullsafety
  charcode: ^1.2.0-nullsafety
  cli_repl: ^0.2.1-nullsafety
  collection: ^1.15.0-nullsafety
  meta: ^1.3.0-nullsafety
  node_interop: "^1.1.0"
  js: ^0.6.3-nullsafety
  package_resolver: "^1.0.0"
  path: ^1.8.0-nullsafety
  source_maps: ^0.10.10-nullsafety
  source_span: ^1.8.0-nullsafety
  stack_trace: ^1.10.0-nullsafety
  stream_transform: ^2.0.0-nullsafety
  string_scanner: ^1.1.0-nullsafety
  term_glyph: ^1.2.0-nullsafety
  tuple: ^2.0.0-nullsafety
  watcher: "^0.9.6"

dev_dependencies:
  archive: ">=1.0.0 <3.0.0"
  analyzer: "^0.40.0"
  cli_pkg: "^1.1.0"
  crypto: ">=0.9.2 <3.0.0"
  dart_style: "^1.2.0"
  grinder: "^0.8.0"
  node_preamble: "^1.1.0"
  pedantic: "^1.0.0"
  pub_semver: "^1.0.0"
  source_span: "^1.5.2"
  stream_channel: ">=1.0.0 <3.0.0"
  test_descriptor: "^1.1.0"
  test_process: "^1.0.0-rc.1"
  test: ^1.16.0-nullsafety
  yaml: "^2.0.0"

dependency_overrides:
  path:
    git: {url: git://github.com/dart-lang/path, ref: path-set-null}
  tuple:
    git: {url: git://github.com/google/tuple.dart}
  stream_transform:
    git: {url: git://github.com/dart-lang/stream_transform}
